kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "0.0.0.0"   # listen on all host interfaces
  apiServerPort: 6443           # map to host:6443
name: dev-kt-k8s
nodes:
- role: control-plane
- role: worker
- role: worker