version: '3.8'

services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: always
    ports:
      - "8081:8081" # Nexus web UI
    volumes:
      - nexus_data:/nexus-data
    environment:
      - NEXUS_MAX_ALLOWED_MEMORY=2g # Recommended for production
    networks:
      - ci-cd-network

volumes:
  nexus_data:

networks:
  ci-cd-network:
    external: true