version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80" # Maps port 80 on the host to port 80 in the container
    volumes:
      # Mount the local nginx.conf to the container's default config location
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - ci-cd-network

networks:
  ci-cd-network:
    external: true